export const SATELLITES_LIST = {
  earth: [
    {
      id: "SAT-001",
      name: "Horizon Scout",
      objective: "Observação terrestre",
      apoastro: "800 km",
      periastro: "400 km",
      telemetry: "Ativo",
      latency: "120 ms",
      signal: "Alta",
      radius: 80,
      duration: 6000,
      energy: "Solar",
      status: "Órbita estável",
    },
    {
      id: "SAT-002",
      name: "Climate Watcher",
      objective: "Monitoramento climático",
      apoastro: "900 km",
      periastro: "500 km",
      telemetry: "Ativo",
      latency: "140 ms",
      signal: "Média",
      radius: 80,
      duration: 9000,
      energy: "Solar",
      status: "Órbita estável",
    },
    {
      id: "SAT-003",
      name: "Deep Earth Probe",
      objective: "Monitoramento profundo",
      apoastro: "1200 km",
      periastro: "700 km",
      telemetry: "Ativo",
      latency: "200 ms",
      signal: "Alta",
      radius: 120,
      duration: 12000,
      energy: "Nuclear",
      status: "Monitoramento profundo",
    },
  ],

  mars: [
    {
      id: "MRS-01",
      name: "Mars Mapper",
      objective: "Mapeamento orbital",
      apoastro: "1100 km",
      periastro: "600 km",
      telemetry: "Ativo",
      latency: "280 ms",
      signal: "Alta",
      radius: 90,
      duration: 7000,
      energy: "Solar",
      status: "Mapeamento orbital",
    },
    {
      id: "MRS-02",
      name: "Polar Observer",
      objective: "Órbita polar",
      apoastro: "1300 km",
      periastro: "800 km",
      telemetry: "Ativo",
      latency: "300 ms",
      signal: "Média",
      radius: 130,
      duration: 11000,
      energy: "Solar",
      status: "Órbita polar",
    },
  ],

  jupiter: [
    {
      id: "JUP-OBS",
      name: "Jupiter Storm Eye",
      objective: "Monitoramento atmosférico",
      apoastro: "5000 km",
      periastro: "3000 km",
      telemetry: "Instável",
      latency: "600 ms",
      signal: "Baixa",
      radius: 120,
      duration: 10000,
      energy: "Nuclear",
      status: "Monitoramento atmosférico",
    },
  ],

  saturn: [
    {
      id: "SAT-RING",
      name: "Ring Analyzer",
      objective: "Análise dos anéis",
      apoastro: "2000 km",
      periastro: "1200 km",
      telemetry: "Ativo",
      latency: "450 ms",
      signal: "Média",
      radius: 120,
      duration: 8000,
      energy: "Solar",
      status: "Análise dos anéis",
    },
  ],
};